name:                Haskell-FileManager
version:             0.1.0.0
github:              "Sagolbah/Haskell-FileManager"
license:             BSD3
author:              "Daniil Boger"
maintainer:          "sagolbah@gmail.com"
copyright:           "2020 Daniil Boger"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Sagolbah/Haskell-FileManager#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- mtl
- directory
- text
- filepath
- time
- containers
- split

library:
  source-dirs: src

executables:
  Haskell-FileManager-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-FileManager
    - optparse-applicative
    - mtl
    - directory
    - filepath
    - time

tests:
  Haskell-FileManager-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-FileManager
    - optparse-applicative
    - mtl
    - containers
    - filepath
    - hspec
    - tasty
    - tasty-hspec
    - split
    - time